
export_plots: true

use_filename_as_sample_name:
  - cutadapt
  - picard

# Run only these modules
run_modules:
  - cutadapt
  - fastqc
  - star
  - samtools
  - picard
  - rna_seqc
  - rseqc
  - salmon

module_order:
  - fastqc:
      name: "FastQC"
      path_filters:
        - "fastqc/*.zip"
  - fastqc:
      name: "FastQC_trimmed"
      path_filters:
        - "fastqc_trimmed/*.zip"
  - cutadapt:
      name: "Cutadapt"
      path_filters:
        - "cutadapt/*"  
  - star:
      name: "STAR"
      path_filters:
        - "star_log/*"
        - "star_count/*"
  - star:
      name: "STAR (graft)"
      path_filters:
        - "star_log_graft/*"
  - star:
      name: "STAR (host)"
      path_filters:
        - "star_log_host/*"
  - salmon:
      name: "Salmon"
      path_filters:
        - "salmon/*"
  - samtools:
      name: "Samtools"
      path_filters:
        - "samtools/*"
  - samtools:
      name: "Samtools (alignment to graft genome)"
      path_filters:
        - "samtools_graft/*"
  - samtools:
      name: "Samtools (excluding reads of host origin)"
      path_filters:
        - "samtools_xeno/*"
  - samtools:
      name: "Samtools (alignment to host genome)"
      path_filters:
        - "samtools_host/*"
  - picard:
      name: "Picard"
      path_filters:
        - "gatk/*"
  - rna_seqc:
      name: "RNA-SeQC"
      path_filters:
        - "rnaseqc/*"
  - rseqc:
      name: "RSeQC"
      path_filters:
        - "rseqc/*"
        