
export_plots: true

# Run only these modules
run_modules:
  - fastqc
  - star
  - samtools
  - picard
  - rna_seqc
  - rseqc

module_order:
  - fastqc:
      name: "FastQC"
      path_filters:
        - "fastqc/*.zip"
  - fastqc:
      name: "FastQC_trimmed"
      path_filters:
        - "fastqc_trimmed/*.zip"
  - star:
      name: "STAR"
      path_filters:
        - "star_log/*"
        - "star_count/*"
  - star:
      name: "STAR (host)"
      path_filters:
        - "star_log_host/*"
        - "star_count_host/*"
  - samtools:
      name: "Samtools"
      path_filters:
        - "samtools/*"
  - picard:
      name: "Picard"
      path_filters:
        - "gatk/*"
  - rna_seqc:
      name: "RNA-SeQC"
      path_filters:
        - "rnaseqc/*"
  - rseqc:
      name: "RSeQC"
      path_filters:
        - "rseqc/*"
        